26 reactions overview
jmajaca/infobot-public pull request #30
Opened 2020-09-28 09:21 UTC by ikrizanic

2020-09-28 14:53 UTC, jmajaca requested changes

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +    search_filter: String
str

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +        # self.logger.info_log("Retrieved top senders.")
ova linija treba il ne treba?

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +        # self.logger.info_log("Retrieved top receivers.")
isto ko gore

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +        Name of reaction user wants to view, defaults to "default"
fali doc za metode i povrati tipovi metoda

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +                all()
se mogu ovdje izbjeć `/` na kraju lajna?

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +    def get_top_senders(self, number_of_senders: int = default_number, search_filter="default"):
drugo ime za `search_filter` da se odma zna šta je

2020-09-28 14:53 UTC, jmajaca commented on src/main/objects/scanner.py
> +    reaction_manager : ReactionScrapper
promijeniti ime varijable

2020-09-28 14:53 UTC, jmajaca commented on src/web_app/web/templates/base.html
> +                    <button style="color: white; cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="no-button">
ne znam jesi ja il ti ovo napravio al stavit style u css

2020-09-28 14:53 UTC, jmajaca commented on src/web_app/web/templates/reaction.html
> +       <div class="row" style="margin-top: 10px; margin-left: 10px">
css

2020-09-28 14:53 UTC, jmajaca commented on src/web_app/web/templates/reaction.html
> +       <div class="row" style="margin-top: 10px; margin-left: 10px">
u cijelom fajlu maknut atribut `style` u css

2020-09-28 14:53 UTC, jmajaca commented on src/web_app/web/templates/reaction.html
> +<script>
prebacit sve u `static/js/reaction.js`

2020-09-28 15:13 UTC, ikrizanic commented on src/web_app/web/templates/base.html
> +                    <button style="color: white; cursor: pointer;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="no-button">
kasnije refaktorirati base.html

2020-09-28 15:26 UTC, ikrizanic commented on src/web_app/web/templates/reaction.html
> +       <div class="row" style="margin-top: 10px; margin-left: 10px">
Problem sa primjenom css-a iz statica na row class

2020-09-28 15:32 UTC, ikrizanic commented on src/web_app/web/templates/reaction.html
> +        </div>
Riješiti margine tablica

2020-10-04 17:39 UTC, jmajaca requested changes

2020-10-04 17:39 UTC, jmajaca commented on src/main/objects/reaction_manager.py
> +    get_latest_reactions(number_of_top: int = default_number, reaction_name="default") -> tuple(sender, receiver, channel, time)
dodatno definirati povratne vrijednosti

2020-10-04 17:46 UTC, jmajaca approved these changes

2020-10-10 17:39 UTC, merged